### ISSUE TITLE
Request: Externalize internal functions

### ISSUE THREAD

**Issue by wei3erHase** [defi-wonderland/lopt#9]
It'd be amazing to have a way of externalizing the internal functions so that we avoid writing them down in for-test contracts.
```solidity
ContractForTest is Contract {
    function myInternalFunction(){
        return _myInternalFunction()
    }
}
```

I understand that they would not be possible to get from the interface, but they should from the contract, and all of them should respond to `_functionName`.

Since they would be impossible to call with `Contract._functionName()` I'd say some naming could be `Contract.internal_functionName()`

**Comment by kiwi745** [comment]
Interesting, I am not sure that it is even possible, but I will check it out and let you know
